import type { ActionDefinition } from "@/types/actions";

export const BUILTIN_ACTIONS: ActionDefinition[] = [
  {
    id: "builtin-open-trade",
    name: "OpenTrade",
    description: "Opens barter menu with the NPC",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-accompany-target",
    name: "AccompanyTarget",
    description: "NPC follows the player",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-stop-accompanying",
    name: "StopAccompanying",
    description: "NPC stops following the player",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-wait-here",
    name: "WaitHere",
    description: "NPC waits at current location",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-slap-target",
    name: "SlapTarget",
    description: "NPC slaps the target (non-lethal)",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-gesture",
    name: "Gesture",
    description: "NPC performs an animation gesture",
    parameterSchema: '{"anim": "applaud|laugh|wave|bow|shrug|angry|scared|bored"}',
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-companion-follow",
    name: "CompanionFollow",
    description: "Companion resumes following the player",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-companion-wait",
    name: "CompanionWait",
    description: "Companion waits at current location",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-companion-inventory",
    name: "CompanionInventory",
    description: "Opens companion inventory for item exchange",
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-companion-give-task",
    name: "CompanionGiveTask",
    description: "Assigns a task to companion",
    parameterSchema: '{"task": "description of the task"}',
    category: "builtin",
    enabled: true,
  },
  {
    id: "builtin-rent-room",
    name: "RentRoom",
    description: "Rents a room at an inn",
    category: "builtin",
    enabled: true,
  },
];

export const DEFAULT_CUSTOM_ACTIONS: ActionDefinition[] = [
  {
    id: "custom-attack",
    name: "Attack",
    description: "NPC attacks the target with equipped weapon",
    category: "custom",
    enabled: true,
  },
  {
    id: "custom-draw-weapon",
    name: "DrawWeaponAndThreaten",
    description: "NPC draws weapon and threatens the target",
    category: "custom",
    enabled: true,
  },
  {
    id: "custom-stop-fighting",
    name: "StopFighting",
    description: "NPC sheathes weapon and stops combat",
    category: "custom",
    enabled: true,
  },
  {
    id: "custom-drink-health",
    name: "DrinkHealthPotion",
    description: "NPC drinks a health potion",
    category: "custom",
    enabled: false,
  },
  {
    id: "custom-drink-magicka",
    name: "DrinkMagickaPotion",
    description: "NPC drinks a magicka potion",
    category: "custom",
    enabled: false,
  },
  {
    id: "custom-drink-stamina",
    name: "DrinkStaminaPotion",
    description: "NPC drinks a stamina potion",
    category: "custom",
    enabled: false,
  },
  {
    id: "custom-give-gold",
    name: "GiveGold",
    description: "NPC gives gold to the target",
    parameterSchema: '{"amount": "number of gold coins"}',
    category: "custom",
    enabled: false,
  },
  {
    id: "custom-start-brawl",
    name: "StartBrawl",
    description: "NPC initiates a non-lethal fistfight",
    category: "custom",
    enabled: true,
  },
];
